language: java

jdk:
  - openjdk8

script:
  - chmod +x ./gradlew
  - ./gradlew build

after_success:
  - wget https://gist.githubusercontent.com/ChiquitaV2/051e9d47b6e8d3693d86c620f359854f/raw/f4344cd9704dd3d9578b143e335919d838f57319/discordHook.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL $UPLOADHOOK_URL
after_failure:
  - wget https://gist.githubusercontent.com/ChiquitaV2/051e9d47b6e8d3693d86c620f359854f/raw/f4344cd9704dd3d9578b143e335919d838f57319/discordHook.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL $UPLOADHOOK_URL